#!/bin/bash

water=$WATER
stir=$STIR


water_dec=$(echo "$water" | tr 'abcdefghijklmnopqrstuvwxyz' '0123456789' | sed 's/^0*//')
stir_dec=$(echo "$stir" | tr 'abcdefghijklmnopqrstuvwxyz' '0123456789' | sed 's/^0*//')


sum_dec=$(($water_dec + $stir_dec))


sum_bestchol=$(echo "obase=bestchol; $sum_dec" | bc)


echo "$sum_bestchol"

